..\obj\hw_config.o: ..\USB\CONFIG\hw_config.c
..\obj\hw_config.o: ..\SYSTEM\sys\sys.h
..\obj\hw_config.o: ..\SYSTEM\sys\stm32f10x_map.h
..\obj\hw_config.o: ..\SYSTEM\sys\stm32f10x_conf.h
..\obj\hw_config.o: ..\SYSTEM\sys\stm32f10x_type.h
..\obj\hw_config.o: ..\SYSTEM\sys\cortexm3_macro.h
..\obj\hw_config.o: ..\SYSTEM\sys\stm32f10x_nvic.h
..\obj\hw_config.o: ..\USB\CONFIG\hw_config.h
..\obj\hw_config.o: ..\USB\LIB\usb_type.h
..\obj\hw_config.o: ..\USB\CONFIG\usb_conf.h
..\obj\hw_config.o: ..\USER\usb_lib.h
..\obj\hw_config.o: ..\USB\LIB\usb_regs.h
..\obj\hw_config.o: ..\USB\LIB\usb_def.h
..\obj\hw_config.o: ..\USB\LIB\usb_core.h
..\obj\hw_config.o: ..\USB\LIB\usb_init.h
..\obj\hw_config.o: ..\USB\LIB\usb_mem.h
..\obj\hw_config.o: ..\USB\LIB\usb_int.h
..\obj\hw_config.o: ..\USB\CONFIG\usb_desc.h
..\obj\hw_config.o: ..\USB\CONFIG\platform_config.h
..\obj\hw_config.o: ..\USB\CONFIG\usb_pwr.h
