.\output\usb_core.o: ..\Libraries\STM32_USB_OTG_Driver\src\usb_core.c
.\output\usb_core.o: ..\Libraries\STM32_USB_OTG_Driver\inc\usb_core.h
.\output\usb_core.o: .\inc\usb_conf.h
.\output\usb_core.o: ..\Libraries\CM3\stm32f10x.h
.\output\usb_core.o: ..\Libraries\CM3\core_cm3.h
.\output\usb_core.o: C:\Keil\ARM\ARMCC\bin\..\include\stdint.h
.\output\usb_core.o: ..\Libraries\CM3\system_stm32f10x.h
.\output\usb_core.o: ..\App\stm32f10x_conf.h
.\output\usb_core.o: ..\Libraries\STM32F10x_StdPeriph_Driver\inc\stm32f10x_can.h
.\output\usb_core.o: ..\Libraries\CM3\stm32f10x.h
.\output\usb_core.o: ..\Libraries\STM32F10x_StdPeriph_Driver\inc\stm32f10x_exti.h
.\output\usb_core.o: ..\Libraries\STM32F10x_StdPeriph_Driver\inc\stm32f10x_gpio.h
.\output\usb_core.o: ..\Libraries\STM32F10x_StdPeriph_Driver\inc\stm32f10x_rcc.h
.\output\usb_core.o: ..\Libraries\STM32F10x_StdPeriph_Driver\inc\stm32f10x_tim.h
.\output\usb_core.o: ..\Libraries\STM32F10x_StdPeriph_Driver\inc\stm32f10x_usart.h
.\output\usb_core.o: ..\Libraries\STM32F10x_StdPeriph_Driver\inc\misc.h
.\output\usb_core.o: ..\Libraries\STM32_USB_OTG_Driver\inc\usb_regs.h
.\output\usb_core.o: ..\Libraries\STM32_USB_OTG_Driver\inc\usb_defines.h
.\output\usb_core.o: ..\Libraries\STM32_USB_OTG_Driver\inc\usb_bsp.h
