..\obj\pcr_control.o: PCR_Control.c
..\obj\pcr_control.o: ..\SYSTEM\sys\sys.h
..\obj\pcr_control.o: ..\SYSTEM\sys\stm32f10x_map.h
..\obj\pcr_control.o: ..\SYSTEM\sys\stm32f10x_conf.h
..\obj\pcr_control.o: ..\SYSTEM\sys\stm32f10x_type.h
..\obj\pcr_control.o: ..\SYSTEM\sys\cortexm3_macro.h
..\obj\pcr_control.o: ..\SYSTEM\sys\stm32f10x_nvic.h
..\obj\pcr_control.o: ..\SYSTEM\delay\delay.h
..\obj\pcr_control.o: ..\HARDWARE\RTC\rtc.h
..\obj\pcr_control.o: ..\HARDWARE\ADC\adc.h
..\obj\pcr_control.o: ..\HARDWARE\DMA\dma.h
..\obj\pcr_control.o: ..\HARDWARE\SPI\spi.h
..\obj\pcr_control.o: ..\USER\user_def.h
..\obj\pcr_control.o: ..\USER\build_cfg.h
..\obj\pcr_control.o: PCR_Cycle.h
..\obj\pcr_control.o: Temperature.h
